-include("kvs.hrl").

-record(user, {?ITERATOR(feed, true),
        email,
        username,
        display_name,
        password,
        tokens,
        avatar,
        name = undefined,
        surname = undefined,
        age,
        sex,
        location,
        education,
        register_date,
        status,
        verification_code,
        zone,
        type,
        comments,
        discussions,
        transactions,
        team,
        aclver}).
